version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=Europe/Moscow"
      - "POSTGRES_USER=otus"
      - "POSTGRES_PASSWORD=otus"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"